import { lstatSync } from "node:fs";
import { dirname, join, sep } from "node:path";

export const CONTEXT_FILE_MARKER =
  "<!-- Generated by airules. Edit .airules.yml, then run airules sync. -->";

export function isContextTool(tool: string): boolean {
  return tool === "gemini" || tool === "qwen";
}

export function isManagedContextFile(content: string): boolean {
  // Preserve ownership across Windows checkouts/editors, including UTF-8 BOMs.
  const firstLine = content.replace(/^\uFEFF/, "").split(/\r?\n/, 1)[0];
  return firstLine === CONTEXT_FILE_MARKER;
}

export function assertContextFileSafe(cwd: string, relativePath: string): void {
  // Legacy .gemini/rules.md must not be read through a directory alias either.
  let parentPath = cwd;
  for (const segment of dirname(relativePath).split(sep)) {
    if (segment === ".") continue;
    parentPath = join(parentPath, segment);
    const parent = lstatSync(parentPath, { throwIfNoEntry: false });
    if (parent && !parent.isDirectory()) {
      throw new Error(`Refusing to use ${relativePath}: context directories must not be aliases.`);
    }
  }
  const file = lstatSync(join(cwd, relativePath), { throwIfNoEntry: false });
  if (file && (!file.isFile() || file.nlink > 1)) {
    throw new Error(
      `Refusing to use ${relativePath}: context must be a regular file with a single link.`,
    );
  }
}
