import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { airulesConfigSchema } from "../../src/core/config/schema.js";
import { detectProject } from "../../src/core/detector/index.js";
import { isContextTool, isManagedContextFile } from "../../src/core/generator/context-file.js";
import { GeminiGenerator } from "../../src/core/generator/gemini.js";
import { generateAll, getGeneratorInfo } from "../../src/core/generator/index.js";
import { QwenGenerator } from "../../src/core/generator/qwen.js";
import { GENERATOR_MAP } from "../../src/core/generator/types.js";
import { scoreProject } from "../../src/core/scorer/index.js";

let cwd: string;
beforeEach(() => {
  cwd = mkdtempSync(join(tmpdir(), "airules-context-generator-"));
});
afterEach(() => rmSync(cwd, { recursive: true, force: true }));

const config = airulesConfigSchema.parse({
  project: { name: "fixture", stack: "nextjs", language: "typescript" },
  targets: ["gemini", "qwen"],
  rules: {
    style: {
      naming_convention: "snake_case",
      import_style: "mixed",
      quote_style: "single",
      prefer_functional: true,
    },
    architecture: { pattern: "domain-driven", api_style: "graphql" },
    testing: { framework: "vitest" },
    git: { commit_style: "gitmoji" },
  },
  custom: ["Keep public APIs stable"],
});

describe("context generators", () => {
  it("preserves the exact Gemini-specific conventions", async () => {
    const content = new GeminiGenerator().generate(await detectProject(cwd), config);
    expect(content).toBe(`<!-- Generated by airules. Edit .airules.yml, then run airules sync. -->

# Gemini Rules for fixture
Stack: nextjs (typescript)

## Code Style
- Use snake_case naming
- Use mixed imports
- Use single quotes

## Architecture
- Pattern: domain-driven
- API Style: graphql

## Custom Rules
- Keep public APIs stable
`);
    expect(isManagedContextFile(content)).toBe(true);
    expect(isManagedContextFile("# My context\n")).toBe(false);
    expect(isContextTool("gemini")).toBe(true);
    expect(isContextTool("claude")).toBe(false);
  });

  it("preserves the exact Qwen-specific conventions", async () => {
    const content = new QwenGenerator().generate(await detectProject(cwd), config);
    expect(content).toBe(`<!-- Generated by airules. Edit .airules.yml, then run airules sync. -->

# Qwen Code Rules for fixture
Stack: nextjs (typescript)

- Naming: snake_case
- Imports: mixed
- Quotes: single
- Prefer functional programming patterns
- Architecture: domain-driven
- Testing: vitest
- Git: gitmoji

## Custom Rules
- Keep public APIs stable
`);
    expect(isManagedContextFile(content)).toBe(true);
    expect(isContextTool("qwen")).toBe(true);
  });

  it("keeps generation, generator metadata, and scoring paths in agreement", async () => {
    const profile = await detectProject(cwd);
    const results = generateAll(profile, config, cwd, true);
    expect(results.map(({ path }) => path)).toEqual(["GEMINI.md", "QWEN.md"]);
    for (const result of results) {
      expect(getGeneratorInfo(result.tool)?.outputPath).toBe(result.path);
      expect(GENERATOR_MAP[result.tool]).toBe(result.path);
    }
    const otherFiles = Object.values(GENERATOR_MAP).filter(
      (path) => !["GEMINI.md", "QWEN.md"].includes(path),
    );
    const { suggestions } = scoreProject(profile, config, otherFiles);
    expect(suggestions).toContainEqual({
      message: "Consider adding rules for: QWEN.md, GEMINI.md",
      priority: "low",
    });
    expect(
      JSON.stringify(scoreProject(profile, config, [...otherFiles, "GEMINI.md", "QWEN.md"])),
    ).not.toContain("Consider adding rules for");
  });
});
